/* --- Modo apagão: conta o tempo sem luz e lembra o que fazer --- */
const APAGAO_INICIO = EN ? ['Check whether it is just your home (fuse box) or the whole area (neighbours, street, radio)', 'Unplug the computer, the TV and any appliances with electronics', 'Leave one light switched on so you know when the power comes back', 'Fill bottles and the bath while there is still water pressure', 'Turn on the battery radio or the car radio', 'Send an SMS to the family and agree on the meeting point', 'Put your phone in Low Power Mode and aeroplane mode'] : ['Ver se é só em casa (quadro elétrico) ou geral (vizinhos, rua, rádio)', 'Desligar da tomada o computador, a televisão e os aparelhos com eletrónica', 'Deixar uma luz ligada para saber quando a energia volta', 'Encher garrafas e a banheira enquanto há pressão', 'Ligar o rádio a pilhas ou o do carro', 'Enviar SMS à família e combinar o ponto de encontro', 'Pôr o telemóvel em poupança de energia e em modo de voo'];
const APAGAO_HORAS = EN ? ['Keep the fridge and freezer closed at all times', 'Use torches instead of candles; candles only under supervision', 'Never use a generator, charcoal or a barbecue indoors', 'Have cash in small notes: Multibanco (cash machines) and cards do not work', 'Drive as little as possible: traffic lights are out, treat junctions as STOP signs', 'Check on neighbours who are elderly, ill or have babies'] : ['Frigorífico e congelador sempre fechados', 'Lanternas em vez de velas; velas só sob vigilância', 'Gerador, carvão e grelhadores nunca dentro de casa', 'Dinheiro em notas pequenas: multibanco e cartões não funcionam', 'Conduzir o menos possível: semáforos apagados, cruzamentos como STOP', 'Ir ver dos vizinhos idosos, doentes ou com bebés'];
const APAGAO_VOLTOU = EN ? ['Switch appliances back on a few at a time, with gaps in between', 'Check the food in the fridge and freezer', 'Restock water and batteries and note down what was missing'] : ['Ligar os aparelhos aos poucos, com intervalos', 'Ver a comida do frigorífico e do congelador', 'Repor a água e as pilhas e anotar o que faltou'];
function apagaoAviso() {
  const s = LS.get('apagao', null); if (!s || s.fim) return '';
  const m = Math.floor((Date.now() - s.inicio) / 6e4);
  return '<a class="callout warn apg-aviso" href="#/t/apagao"><strong>' + L('Apagão em curso', 'Blackout in progress') + '</strong> ' + L('há ', 'for ') + (m >= 60 ? Math.floor(m / 60) + ' h ' + pad(m % 60) + ' min' : m + ' min') + L('. Ver até quando a comida está segura.', '. See how long the food stays safe.') + '</a>';
}
TOOLS.push({ id: 'apagao', section: 'ferramentas', icon: '🔌', title: L('Modo apagão', 'Blackout mode'), desc: L('Conta há quanto tempo não há luz, diz até quando o frigorífico e o congelador são seguros e lembra o que fazer nas primeiras horas. Funciona sem rede.', 'Counts how long the power has been off, tells you how long the fridge and freezer stay safe and reminds you what to do in the first hours. Works without a network.'),
  render(el) {
    let s = LS.get('apagao', null), timer = null;
    const hm = ts => new Date(ts).toLocaleTimeString(LOCALE, { hour: '2-digit', minute: '2-digit' });
    const quandoFim = ts => new Date(ts).toDateString() === new Date().toDateString() ? L('às ' + hm(ts), hm(ts)) : new Date(ts).toLocaleDateString(LOCALE, { weekday: 'long' }) + L(' às ', ' at ') + hm(ts);
    const dur = ms => { const m = Math.max(0, Math.floor(ms / 6e4)), h = Math.floor(m / 60); return h ? h + ' h ' + pad(m % 60) + ' min' : m + ' min'; };
    const guarda = () => LS.set('apagao', s);
    const lista = (id, itens) => '<ul class="list">' + itens.map((t, i) => { const k = id + i, ok = !!(s.feito && s.feito[k]); return '<li><label class="row" style="flex:1"><input type="checkbox" class="fixed" data-k="' + k + '"' + (ok ? ' checked' : '') + '><span style="flex:1' + (ok ? ';text-decoration:line-through;opacity:.6' : '') + '">' + esc(t) + '</span></label></li>'; }).join('') + '</ul>';
    const barra = (horas, titulo, extra) => {
      const fim = s.inicio + horas * 36e5, now = Date.now(), pct = Math.min(100, (now - s.inicio) / (horas * 36e5) * 100), passou = now >= fim, cor = passou ? 'danger' : pct > 75 ? 'warn' : 'ok';
      return '<div class="card"><div class="row"><strong style="flex:1">' + titulo + '</strong><span class="badge ' + cor + '">' + (passou ? L('deixou de ser seguro ', 'no longer safe since ') + quandoFim(fim) : L('seguro até ', 'safe until ') + quandoFim(fim)) + '</span></div><div class="progress"><div style="width:' + pct.toFixed(1) + '%;background:var(--' + cor + ')"></div></div>' + (extra || '') + '</div>';
    };
    const ligaChecks = () => $$('[data-k]', el).forEach(c => c.onchange = () => { s.feito = s.feito || {}; if (c.checked) s.feito[c.dataset.k] = Date.now(); else delete s.feito[c.dataset.k]; guarda(); draw(); });
    const draw = () => {
      clearInterval(timer); timer = null;
      if (!s || s.fim) {
        const ult = s && s.fim ? s : null, d = ult ? ult.fim - ult.inicio : 0;
        el.innerHTML = (ult ? '<div class="card"><h3>✅ ' + L('A luz voltou às ', 'The power came back at ') + hm(ult.fim) + '</h3><p>' + L('Esteve ' + dur(d) + ' sem luz, desde ', 'The power was off for ' + dur(d) + ', from ') + esc(fmtDate(ult.inicio)) + '.</p>' +
          (d > 4 * 36e5 ? md(L('>! **Frigorífico:** deita fora a carne, o peixe, os lacticínios, os ovos e os restos que estiveram acima de 5 °C mais de 2 horas. Em dúvida, deita fora.', '>! **Fridge:** throw away meat, fish, dairy products, eggs and leftovers that have been above 5 °C for more than 2 hours. If in doubt, throw it out.'), 'apgf') : '<p class="small">' + L('O frigorífico esteve menos de 4 horas sem luz: se ficou fechado, a comida está segura.', 'The fridge was without power for less than 4 hours: if it stayed closed, the food is safe.') + '</p>') +
          (d > (ult.cong === 'meio' ? 24 : 48) * 36e5 ? md(L('>! **Congelador:** o que ainda tem cristais de gelo pode voltar a congelar. O que descongelou, cheira mal ou esteve acima de 5 °C mais de 2 horas vai para o lixo.', '>! **Freezer:** anything that still has ice crystals can be refrozen. Anything that has thawed, smells bad or has been above 5 °C for more than 2 hours goes in the bin.'), 'apgc') : '') +
          '<h3>' + L('Quando a energia volta', 'When the power comes back') + '</h3>' + lista('v', APAGAO_VOLTOU) + field(L('O que faltou (para comprar ou preparar)', 'What was missing (to buy or prepare)'), '<textarea id="anotas">' + esc(ult.notas || '') + '</textarea>') + '<div class="btnrow"><button class="btn" id="aapagar">' + L('Apagar este registo', 'Delete this record') + '</button></div></div>' : '') +
          '<div class="card"><h3>' + L('Começou um apagão?', 'Has a blackout started?') + '</h3><p class="small">' + L('Carrega quando a luz for abaixo: a app conta o tempo e diz até quando a comida está segura, mesmo que a feches.', 'Tap when the power goes off: the app keeps track of the time and tells you how long the food stays safe, even if you close it.') + '</p><button class="btn huge primary" id="acomecar">💡 ' + L('Começou agora', 'It started just now') + '</button><div class="row" style="margin-top:.6em"><label class="field"><span>' + L('Ou começou mais cedo, às', 'Or it started earlier, at') + '</span><input type="time" id="ahora"></label><button class="btn fixed" id="acomecarh">' + L('Começou a esta hora', 'It started at this time') + '</button></div></div>' +
          '<p class="small"><a href="#/s/agora/apagao">' + L('O que fazer num apagão', 'What to do in a blackout') + '</a> · <a href="#/s/casa/apagao-casa">' + L('Casa sem eletricidade', 'Home without electricity') + '</a> · <a href="#/t/bateria">' + L('Poupar bateria', 'Save battery') + '</a></p>';
        const comecar = ts => { s = { inicio: ts, fim: 0, cong: (ult && ult.cong) || 'cheio', feito: {} }; guarda(); draw(); };
        $('#acomecar', el).onclick = () => comecar(Date.now());
        $('#acomecarh', el).onclick = () => { const v = $('#ahora', el).value; if (!v) return toast(L('Escolhe a hora', 'Choose the time')); const p = v.split(':').map(Number), d0 = new Date(); d0.setHours(p[0], p[1], 0, 0); if (+d0 > Date.now()) d0.setDate(d0.getDate() - 1); comecar(+d0); };
        if (ult) { ligaChecks(); $('#anotas', el).oninput = e => { s.notas = e.target.value; guarda(); }; $('#aapagar', el).onclick = () => { s = null; LS.del('apagao'); draw(); }; }
        return;
      }
      const now = Date.now(), prox = new Date(now); prox.setMinutes(0, 0, 0); prox.setHours(prox.getHours() + 1);
      el.innerHTML = '<div class="card center"><div class="small muted">' + L('Sem luz desde as ', 'No power since ') + hm(s.inicio) + '</div><div class="bigdisplay">' + dur(now - s.inicio) + '</div><button class="btn big ok" id="avoltou">✅ ' + L('A luz voltou', 'The power is back') + '</button></div>' +
        barra(4, '🧊 ' + L('Frigorífico fechado: 4 horas', 'Fridge kept closed: 4 hours')) +
        barra(s.cong === 'meio' ? 24 : 48, '❄️ ' + L('Congelador ' + (s.cong === 'meio' ? 'meio cheio: 24 horas' : 'cheio: 48 horas'), s.cong === 'meio' ? 'Half-full freezer: 24 hours' : 'Full freezer: 48 hours'), '<div class="btnrow"><button class="btn sm' + (s.cong !== 'meio' ? ' primary' : '') + '" data-cong="cheio">' + L('Cheio', 'Full') + '</button><button class="btn sm' + (s.cong === 'meio' ? ' primary' : '') + '" data-cong="meio">' + L('Meio cheio', 'Half full') + '</button></div>') +
        '<div class="card"><strong>📱 ' + L('Telemóvel', 'Phone') + '</strong><p class="small">' + L('Modo de voo e poupança de energia. Liga a rede 5 minutos às horas certas para receber mensagens: a próxima é às ', 'Aeroplane mode and Low Power Mode. Switch the network on for 5 minutes on the hour to receive messages: the next time is at ') + '<strong>' + hm(+prox) + '</strong>.</p><div class="btnrow"><a class="btn sm" href="#/t/mensagens">💬 ' + L('SMS à família', 'SMS to family') + '</a><a class="btn sm" href="#/t/lanterna">🔦 ' + L('Lanterna', 'Torch') + '</a></div></div>' +
        '<div class="card"><strong>📻 ' + L('Rádio', 'Radio') + '</strong><p class="small">' + L('Liga ', 'Tune in to ') + esc(radioZonaTexto(minhaZona())) + '.</p><a class="btn sm" href="#/t/mensagens">' + L('Todas as frequências', 'All frequencies') + '</a></div>' +
        '<div class="card"><h3>' + L('Primeiros minutos', 'First few minutes') + '</h3>' + lista('i', APAGAO_INICIO) + '</div><div class="card"><h3>' + L('Nas horas seguintes', 'In the hours that follow') + '</h3>' + lista('h', APAGAO_HORAS) + '</div>' +
        '<p class="small muted">' + L('A contagem continua com a app fechada. Guia completo: <a href="#/s/agora/apagao">Apagão</a>.', 'The timer keeps running with the app closed. Full guide: <a href="#/s/agora/apagao">Blackout</a>.') + '</p>';
      $('#avoltou', el).onclick = () => { s.fim = Date.now(); guarda(); draw(); };
      $$('[data-cong]', el).forEach(b => b.onclick = () => { s.cong = b.dataset.cong; guarda(); draw(); });
      ligaChecks();
      timer = setInterval(() => { if (document.visibilityState === 'visible') draw(); }, 60000);
    };
    draw();
    return () => clearInterval(timer);
  } });
