/* --- Alertas no telemóvel (GitHub + ntfy) e «Perto de mim» --- */
const NTFY_SERVIDOR = 'https://ntfy.sh/';
function alertasCfg() { return Object.assign({ zonas: [], ipma: 'laranja', sismosPerto: true, sismosPortugal: true, rcm: true, mundo: true, topico: '', link: '' }, LS.get('alertasCfg', {}) || {}); }
function alertasTopico() { const a = new Uint8Array(16); crypto.getRandomValues(a); return 'safety-' + Array.from(a, b => 'abcdefghijkmnpqrstuvwxyz23456789'[b % 32]).join(''); }
TOOLS.push({ id: 'alertas', section: 'ferramentas', icon: '🔔', title: L('Alertas no telemóvel', 'Phone alerts'), desc: L('Recebe no telemóvel, mesmo com a app fechada, os avisos do IPMA da tua zona, os sismos sentidos perto, o risco máximo de incêndio e as catástrofes graves no mundo. Grátis, com o GitHub e a app ntfy.', 'Get the IPMA (weather institute) warnings for your area, earthquakes felt nearby, maximum fire danger and major disasters around the world on your phone, even with the app closed. Free, with GitHub and the ntfy app.'),
  render(el) {
    const cfg = alertasCfg();
    if (!cfg.topico) cfg.topico = alertasTopico();
    if (!cfg.zonas.length && minhaZona()) cfg.zonas = [minhaZona()];
    if (!cfg.link && /\.github\.io$/i.test(location.hostname)) cfg.link = location.origin + location.pathname;
    const guarda = () => LS.set('alertasCfg', cfg);
    guarda();
    const draw = () => {
      const json = JSON.stringify(Object.assign({ zonas: cfg.zonas, ipma: cfg.ipma, sismosPerto: cfg.sismosPerto, sismosPortugal: cfg.sismosPortugal, rcm: cfg.rcm, mundo: cfg.mundo, link: cfg.link }, EN ? { idioma: 'en' } : {})), teste = LS.get('alertasTeste', 0);
      const chk = (k, t) => '<label class="field row"><input type="checkbox" class="fixed" data-cfg="' + k + '"' + (cfg[k] ? ' checked' : '') + '><span style="flex:1">' + t + '</span></label>';
      const opt = (v, t) => '<option value="' + v + '"' + (cfg.ipma === v ? ' selected' : '') + '>' + t + '</option>';
      el.innerHTML = md(L('>i Com a app fechada e o telemóvel bloqueado, recebes uma notificação quando houver um aviso para a tua zona. Um serviço gratuito do GitHub verifica as fontes oficiais de 10 em 10 minutos e envia o alerta pela app **ntfy** (gratuita, sem conta). Não substitui os SMS de alerta da Proteção Civil.', '>i With the app closed and the phone locked, you get a notification when there is a warning for your area. A free GitHub service checks the official sources every 10 minutes and sends the alert through the **ntfy** app (free, no account). It does not replace the SMS alerts from Proteção Civil (Civil Protection).'), 'alinfo') +
        '<div class="card"><h3>' + L('1. Zonas e alertas', '1. Areas and alerts') + '</h3><div class="fambar">' + Object.keys(NEWS_AREAS).map(k => '<label class="btn sm' + (cfg.zonas.indexOf(k) >= 0 ? ' primary' : '') + '"><input type="checkbox" data-zona="' + k + '"' + (cfg.zonas.indexOf(k) >= 0 ? ' checked' : '') + ' style="display:none">' + esc(NEWS_AREAS[k]) + '</label>').join('') + '</div>' +
        '<label class="field"><span>' + L('Avisos meteorológicos do IPMA', 'IPMA weather warnings') + '</span><select id="alipma">' + opt('amarelo', L('Amarelo, laranja e vermelho', 'Yellow, orange and red')) + opt('laranja', L('Laranja e vermelho (recomendado)', 'Orange and red (recommended)')) + opt('vermelho', L('Só vermelho', 'Red only')) + opt('nao', L('Não quero', 'None')) + '</select></label>' +
        chk('sismosPerto', L('Sismos de magnitude 3,5 ou mais a menos de 150 km das zonas', 'Earthquakes of magnitude 3.5 or more within 150 km of the areas')) + chk('sismosPortugal', L('Sismos de magnitude 5 ou mais no continente, nos Açores, na Madeira e no mar à volta', 'Earthquakes of magnitude 5 or more on the mainland, in the Açores, in Madeira and in the surrounding sea')) + chk('rcm', L('Risco máximo de incêndio rural no distrito (uma vez por dia, durante o dia)', 'Maximum wildfire danger in the district (once a day, during the day)')) + chk('mundo', L('Catástrofes com alerta vermelho no mundo e sismos de magnitude 7 ou mais', 'Disasters with a red alert around the world, and earthquakes of magnitude 7 or more')) + '</div>' +
        '<div class="card"><h3>' + L('2. A app ntfy no telemóvel', '2. The ntfy app on your phone') + '</h3><ol class="small"><li>' + L('Instala a app <strong>ntfy</strong> na App Store ou no Google Play. É gratuita e não pede conta.', 'Install the <strong>ntfy</strong> app from the App Store or Google Play. It is free and does not ask for an account.') + '</li><li>' + L('Abre-a, toca em <strong>+</strong> e escreve este tópico:', 'Open it, tap <strong>+</strong> and type this topic in <strong>Topic name</strong>, then tap <strong>Subscribe</strong>:') + '</li></ol><div class="al-topico mono">' + esc(cfg.topico) + '</div><div class="btnrow"><button class="btn" id="alcopt">' + L('📋 Copiar o tópico', '📋 Copy the topic') + '</button><button class="btn sm" id="alnovo">' + L('Criar outro tópico', 'Create another topic') + '</button></div><p class="small muted">' + L('O tópico funciona como uma palavra-passe: quem o souber recebe os mesmos alertas. Dá-o só à família.', 'The topic works like a password: anyone who knows it gets the same alerts. Only give it to your family.') + '</p></div>' +
        '<div class="card"><h3>' + L('3. Testar', '3. Test') + '</h3><p class="small">' + L('Com internet, a app envia uma notificação para o tópico. Deve chegar ao telemóvel em segundos.', 'With internet, the app sends a notification to the topic. It should reach your phone within seconds.') + '</p><div class="btnrow"><button class="btn primary" id="alteste">' + L('📣 Enviar notificação de teste', '📣 Send test notification') + '</button></div><p class="small" id="alst">' + (teste ? L('✅ Último teste enviado ', '✅ Last test sent ') + esc(nwAgo(teste)) + '.' : '') + '</p></div>' +
        '<div class="card"><h3>' + L('4. Ligar o GitHub (uma vez)', '4. Connect GitHub (once)') + '</h3><ol class="small"><li>' + L('No repositório onde publicaste a app, carrega os ficheiros <strong>tools/alertas.mjs</strong> e <strong>.github/workflows/alertas.yml</strong>.', 'In the repository where you published the app, upload the files <strong>tools/alertas.mjs</strong> and <strong>.github/workflows/alertas.yml</strong>.') + '</li><li>' + L('Em <strong>Settings › Secrets and variables › Actions</strong>, separador <strong>Secrets</strong>, cria <strong>NTFY_TOPICO</strong> com o tópico de cima.', 'In <strong>Settings › Secrets and variables › Actions</strong>, on the <strong>Secrets</strong> tab, click <strong>New repository secret</strong> and create <strong>NTFY_TOPICO</strong> with the topic above.') + '</li><li>' + L('No mesmo separador <strong>Secrets</strong>, cria também <strong>ALERTAS_CONFIG</strong> com este texto (como segredo, as zonas não aparecem nos registos públicos do GitHub):', 'On the same <strong>Secrets</strong> tab, click <strong>New repository secret</strong> again and create <strong>ALERTAS_CONFIG</strong> with this text (as a secret, your areas do not appear in GitHub’s public logs):') + '</li></ol>' + (cfg.zonas.length ? '' : '<div class="callout warn">' + L('Escolhe pelo menos uma zona no passo 1: sem zonas, o GitHub não envia alertas.', 'Choose at least one area in step 1: with no areas, GitHub does not send alerts.') + '</div>') + '<pre class="al-json mono small">' + esc(json) + '</pre><div class="btnrow"><button class="btn" id="alcopj">' + L('📋 Copiar a configuração', '📋 Copy the configuration') + '</button></div>' +
        '<ol class="small" start="4"><li>' + L('Em <strong>Actions</strong>, abre <strong>Alertas</strong> e carrega em <strong>Run workflow</strong>. Chega a notificação «Safety &amp; Security: alertas ativos», com os avisos em vigor.', 'On the <strong>Actions</strong> tab, open the <strong>Alertas</strong> workflow and click <strong>Run workflow</strong>. You get the notification “Safety &amp; Security: alerts active”, with the warnings in force.') + '</li></ol>' +
        field(L('Endereço da app, que abre ao tocar na notificação', 'App address, opened when you tap the notification'), '<input id="allink" type="url" placeholder="' + L('https://conta.github.io/safety-security/', 'https://username.github.io/safety-security/') + '" value="' + esc(cfg.link) + '">') +
        '<p class="small muted">' + L('Se mudares as zonas ou os alertas, copia outra vez a configuração para o GitHub. Num repositório público, o GitHub desliga os fluxos agendados ao fim de 60 dias sem alterações: se os alertas pararem, volta a ativá-lo em Actions.', 'If you change the areas or the alerts, copy the configuration to GitHub again. If you change the app language later, also update the ALERTAS_CONFIG secret on GitHub to change the language of the notifications. In a public repository, GitHub disables scheduled workflows after 60 days without changes: if the alerts stop, turn the workflow back on in Actions (<strong>Enable workflow</strong>).') + '</p></div>' +
        '<div class="card small">' + L('<strong>Privacidade.</strong> O GitHub e o ntfy.sh só recebem as zonas escolhidas e alertas públicos. Nomes, localização e dados da família nunca saem do telemóvel. O tópico e a configuração ficam guardados como segredos do GitHub: não aparecem no código nem nos registos públicos.', '<strong>Privacy.</strong> GitHub and ntfy.sh only receive the chosen areas and public alerts. Names, location and family data never leave the phone. The topic and the configuration are stored as GitHub secrets: they do not appear in the code or in the public logs.') + '</div>';
      $$('[data-zona]', el).forEach(c => c.onchange = () => { const k = c.dataset.zona; cfg.zonas = cfg.zonas.filter(z => z !== k); if (c.checked) cfg.zonas.push(k); guarda(); draw(); });
      $$('[data-cfg]', el).forEach(c => c.onchange = () => { cfg[c.dataset.cfg] = c.checked; guarda(); draw(); });
      $('#alipma', el).onchange = e => { cfg.ipma = e.target.value; guarda(); draw(); };
      $('#allink', el).onchange = e => { cfg.link = e.target.value.trim(); guarda(); draw(); };
      $('#alcopt', el).onclick = () => copyText(cfg.topico);
      $('#alcopj', el).onclick = () => copyText(json);
      $('#alnovo', el).onclick = () => { if (!confirm(L('Criar outro tópico? Tens de o subscrever outra vez na app ntfy e de o mudar no GitHub.', 'Create another topic? You will have to subscribe to it again in the ntfy app and change it on GitHub.'))) return; cfg.topico = alertasTopico(); guarda(); draw(); };
      $('#alteste', el).onclick = async () => {
        if (!navigator.onLine) return toast(L('Sem ligação à internet', 'No internet connection'));
        const b = $('#alteste', el), s = $('#alst', el), z = cfg.zonas.map(k => NEWS_AREAS[k]).filter(Boolean);
        b.disabled = true; s.textContent = L('A enviar…', 'Sending…');
        try {
          const corpo = { topic: cfg.topico, title: L('Safety & Security: notificação de teste', 'Safety & Security: test notification'), message: L('Os alertas vão chegar a este telemóvel' + (z.length ? ' para ' + joinE(z) : '') + '. Falta ligar o GitHub (passo 4).', 'Alerts will reach this phone' + (z.length ? ' for ' + joinE(z) : '') + '. GitHub still needs to be connected (step 4).'), priority: 4, tags: ['white_check_mark'] };
          if (/^https:\/\//.test(cfg.link)) corpo.click = cfg.link;
          const r = await fetch(NTFY_SERVIDOR, { method: 'POST', body: JSON.stringify(corpo), credentials: 'omit', referrerPolicy: 'no-referrer' });
          if (!r.ok) throw new Error('HTTP ' + r.status);
          LS.set('alertasTeste', Date.now());
          s.textContent = L('✅ Enviada. Se não chegou, confirma o tópico na app ntfy e se as notificações dela estão autorizadas nas definições do telemóvel.', '✅ Sent. If it did not arrive, check the topic in the ntfy app and that its notifications are allowed in the phone settings.');
        } catch (e) { s.textContent = L('Não foi possível enviar: ', 'Could not send: ') + ((e && e.message) || e) + '.'; }
        b.disabled = false;
      };
    };
    draw();
  } });

TOOLS.push({ id: 'perto', section: 'ferramentas', icon: '📍', title: L('Perto de mim', 'Near me'), desc: L('O que interessa à tua zona: avisos do IPMA, risco de incêndio, sismos a menos de 300 km, as centrais nucleares mais próximas e catástrofes à volta. Guarda a última versão para ver sem rede.', 'What matters for your area: IPMA (weather institute) warnings, fire danger, earthquakes within 300 km, the nearest nuclear power plants and disasters nearby. Keeps the latest version so you can see it without signal.'),
  render(el) {
    let gps = null, busy = false, alive = true;
    const draw = () => {
      const z = LS.get('pertoZona', '') || (gps ? zonaMaisPerto(gps) : minhaZona());
      const ref = gps ? { lat: gps.lat, lon: gps.lon } : zonaRef(z), s = situacaoDados(ref, z), now = Date.now();
      let h = '<div class="card"><div class="row"><label class="field"><span>' + L('A minha zona', 'My area') + '</span><select id="pz"><option value="">' + L('Escolher…', 'Choose…') + '</option>' + Object.keys(NEWS_AREAS).map(k => '<option value="' + k + '"' + (k === z ? ' selected' : '') + '>' + esc(NEWS_AREAS[k]) + '</option>').join('') + '</select></label><button class="btn fixed" id="pgps">' + (gps ? L('📍 A usar a tua posição', '📍 Using your location') : L('📍 Usar a minha posição', '📍 Use my location')) + '</button></div>' +
        '<div class="btnrow"><button class="btn primary" id="pup"' + (busy ? ' disabled' : '') + '>' + (busy ? L('🔄 A atualizar…', '🔄 Updating…') : L('🔄 Atualizar', '🔄 Update')) + '</button></div><p class="small muted">' + (s.ts ? L('Dados de ', 'Data from ') + esc(nwAgo(s.ts)) + '.' : L('Ainda sem dados: com internet, carrega em Atualizar.', 'No data yet: with internet, tap Update.')) + (gps ? L(' As distâncias contam a partir da tua posição, que não sai do telemóvel.', ' Distances are measured from your location, which does not leave the phone.') : '') + '</p></div>';
      if (!ref) { el.innerHTML = h + '<p class="muted">' + L('Escolhe a tua zona ou usa a tua posição.', 'Choose your area or use your location.') + '</p>'; ligar(); return; }
      h += '<div class="card"><h3>' + L('⚠️ Avisos meteorológicos: ', '⚠️ Weather warnings: ') + esc(NEWS_AREAS[z] || '') + '</h3>' + (!s.avisos ? '<p class="small muted">' + L('Sem dados.', 'No data.') + '</p>' : s.avisos.lista.length ? '<ul class="nlist">' + s.avisos.lista.map(x => '<li><span class="badge ' + IPMA_LV[x.lv][1] + '">' + IPMA_LV[x.lv][0] + '</span> <strong>' + esc(ipmaTipo(x.tipo)) + '</strong><div class="nmeta">' + (x.ini > now ? L('a partir de ', 'from ') + esc(nwWhen(x.ini)) + ', ' : '') + L('até ', 'until ') + esc(nwWhen(x.fim)) + '</div>' + (x.txt ? '<div class="nsum">' + esc(x.txt) + '</div>' : '') + '</li>').join('') + '</ul>' : '<p>' + L('✅ Sem avisos amarelos, laranja ou vermelhos.', '✅ No yellow, orange or red warnings.') + '</p>') + '</div>';
      if (AREA_DICO[z]) h += '<div class="card"><h3>' + L('🔥 Risco de incêndio rural hoje', '🔥 Wildfire danger today') + '</h3>' + (!s.rcm ? '<p class="small muted">' + L('Sem dados.', 'No data.') + '</p>' : '<p>' + L('O concelho com mais risco no distrito está em ', 'The most at-risk municipality in the district is at ') + '<span class="rcm rcm' + s.rcm.max + '">' + s.rcm.max + '</span> ' + RCM_LV[s.rcm.max] + '.</p><p class="small muted">' + [5, 4, 3, 2, 1].filter(n => s.rcm.n[n]).map(n => s.rcm.n[n] + L(' em ', ' at ') + RCM_LV[n]).join(', ') + '.</p>') + '<p class="small"><a href="https://fogos.pt/" target="_blank" rel="noopener noreferrer">' + L('Incêndios ativos na Fogos.pt', 'Active fires on Fogos.pt') + '</a> · <a href="#/s/agora/incendio-rural">' + L('O que fazer', 'What to do') + '</a></p></div>';
      h += '<div class="card"><h3>' + L('🌍 Sismos a menos de 300 km, últimos 7 dias', '🌍 Earthquakes within 300 km, last 7 days') + '</h3>' + (!s.sismos ? '<p class="small muted">' + L('Sem dados.', 'No data.') + '</p>' : s.sismos.length ? '<ul class="nlist">' + s.sismos.slice(0, 10).map(x => '<li><span class="badge' + (x.m >= 5 ? ' danger' : x.m >= 4 ? ' warn' : '') + '">M ' + esc(nf(x.m)) + '</span>' + L(' a <strong>', ' <strong>') + fmtKm(x.dist) + L('</strong> para ', '</strong> ') + rumoTexto(ref, { lat: x.la, lon: x.lo }) + ' · ' + esc(x.reg) + '<div class="nmeta">' + esc(nwWhen(x.t)) + ' · ' + x.km + L(' km de profundidade', ' km deep') + '</div></li>').join('') + '</ul>' : '<p>' + L('✅ Nenhum sismo de magnitude 2,5 ou mais.', '✅ No earthquakes of magnitude 2.5 or more.') + '</p>') + '<p class="small"><a href="#/t/guia">' + L('Modo emergência', 'Emergency mode') + '</a> · <a href="#/s/agora/sismo">' + L('O que fazer num sismo', 'What to do in an earthquake') + '</a></p></div>';
      const nuc = nuclearesPerto(ref, 3);
      h += '<div class="card"><h3>' + L('☢️ Centrais nucleares mais próximas', '☢️ Nearest nuclear power plants') + '</h3><ul class="nlist">' + nuc.map(c => '<li><strong>' + esc(c.n) + '</strong> (' + esc(c.pais) + ')' + L(' a ' + fmtKm(c.km) + ' para ', ', ' + fmtKm(c.km) + ' ') + rumoTexto(ref, c) + '</li>').join('') + '</ul><p class="small">' + L('Num acidente nuclear: entra, fica e ouve o rádio. Iodo só quando as autoridades disserem. <a href="#/s/guerra/nuclear">Nuclear e radiação</a>.', 'In a nuclear accident: go in, stay in and listen to the radio. Iodine tablets only when the authorities say so. <a href="#/s/guerra/nuclear">Nuclear and radiation</a>.') + '</p><p class="small muted">' + L('Centrais em funcionamento segundo o Wikidata, setembro de 2026.', 'Plants in operation according to Wikidata, September 2026.') + '</p></div>';
      const nc = LS.get('newsCache', {}) || {}, cat = ((nc.gdacs && nc.gdacs.data) || []).filter(x => isFinite(x.la) && isFinite(x.lo)).map(x => Object.assign({}, x, { dist: distKm(ref, { lat: x.la, lon: x.lo }) })).filter(x => x.dist <= 2500).sort((a, b) => a.dist - b.dist);
      h += '<div class="card"><h3>' + L('🚨 Catástrofes a menos de 2500 km', '🚨 Disasters within 2,500 km') + '</h3>' + (!nc.gdacs ? '<p class="small muted">' + L('Sem dados.', 'No data.') + '</p>' : cat.length ? '<ul class="nlist">' + cat.map(x => { const ty = GDACS_T[x.tipo] || [x.tipo, '⚠️']; return '<li><span class="badge ' + (x.lv === 'Red' ? 'danger' : 'orange') + '">' + (x.lv === 'Red' ? L('Vermelho', 'Red') : L('Laranja', 'Orange')) + '</span> ' + ty[1] + ' ' + esc(ty[0]) + (x.pais ? ' · ' + esc(x.pais) : '') + '<div class="nmeta">' + L('a ' + fmtKm(x.dist), fmtKm(x.dist) + ' away') + ' · ' + esc(nwShortDay(x.de)) + '</div></li>'; }).join('') + '</ul>' : '<p>' + L('✅ Sem alertas laranja ou vermelhos por perto.', '✅ No orange or red alerts nearby.') + '</p>') + '<p class="small"><a href="#/t/mapa">' + L('Ver no mapa', 'See on the map') + '</a> · <a href="#/t/alertas">' + L('Receber alertas no telemóvel', 'Get alerts on your phone') + '</a></p></div>';
      el.innerHTML = h; ligar();
    };
    const ligar = () => {
      $('#pz', el).onchange = e => { LS.set('pertoZona', e.target.value); if (e.target.value && !LS.get('newsArea', '')) LS.set('newsArea', e.target.value); draw(); };
      $('#pgps', el).onclick = () => {
        if (gps) { gps = null; return draw(); }
        if (!navigator.geolocation) return toast(L('Este dispositivo não tem localização', 'This device has no location services'));
        toast(L('A obter a posição…', 'Getting your location…'));
        navigator.geolocation.getCurrentPosition(p => { gps = { lat: p.coords.latitude, lon: p.coords.longitude }; if (alive) draw(); }, () => toast(L('Não foi possível obter a posição', 'Could not get your location')), { enableHighAccuracy: false, timeout: 20000, maximumAge: 300000 });
      };
      $('#pup', el).onclick = async () => { if (!navigator.onLine) return toast(L('Sem ligação à internet', 'No internet connection')); busy = true; draw(); await atualizarFontes(['ipma', 'rcm', 'emsc', 'gdacs', 'usgs']); busy = false; if (alive) draw(); };
    };
    draw();
    return () => { alive = false; };
  } });
